 const ADD_TOKEN ='ADD_TOKEN'
 const REMOVE_TOKEN ='REMOVE_TOKEN'
 const ADD_ARTICLES='ADD_ARTICLES'
 const REMOVE_ARTICLES='REMOVE_ARTICLES'

 export default
 {
  ADD_TOKEN,
  REMOVE_TOKEN,
  ADD_ARTICLES,
  REMOVE_ARTICLES
}