 const ADD_TOKEN ='ADD_TOKEN'
 const REMOVE_TOKEN ='REMOVE_TOKEN'
 const ADD_ARTICLES='ADD_ARTICLES'
 const REMOVE_ARTICLES='REMOVE_ARTICLES'
 const ADD_TAGS='ADD_TAGS'
 const REMOVE_TAGS='REMOVE_TAGS'

 export default
 {
  ADD_TOKEN,
  REMOVE_TOKEN,
  ADD_ARTICLES,
  REMOVE_ARTICLES,
  ADD_TAGS,
  REMOVE_TAGS

}